### ISSUE TITLE
Roadmap for this project

### ISSUE THREAD

**Issue by xcaptain** [casbin-net/EFCore-Adapter#2]
This project is still under development, but basic RBAC functions have been tested on my own 
projects, but still a lot of things need to be done, includes:

- [x] `RemoveFilteredPolicy` api
- [x] `SavePolicy` api
- [x] Make `CasbinRule` model configurable from application code, which means the table name, the column names can be changed. see https://github.com/casbin-net/EFCore-Adapter/pull/6
- [x] more unit tests #7
- [x] A consistent package id and namespace to publish to nuget or github package registry
- [x] Update to .NET Core and EFCore 3.1 #12 
- [x] Code coverage badge doesn't work yet.
- [x] No README.
- [x] No nuget badge, download times badge.

I'm a little busy in the day time but would try to optimize this project

**Comment by samchenws** [comment]
I've implemented some of the code and I pull requests.

**Comment by xcaptain** [comment]
@samchenws thanks for the help :)

**Comment by hsluoyz** [comment]
Hi @xcaptain , another task is the CI and code coverage, and the badges like this:

![image](https://user-images.githubusercontent.com/3787410/61437214-17f66b00-a96f-11e9-9734-3b60dbfb214a.png)

**Comment by xcaptain** [comment]
@hsluoyz Sorry for the late reply, I was planning to try out the new github package registry to publish this package but I has beed added to waitlist, so I changed to nuget.org. now the package has been published at https://www.nuget.org/packages/Casbin.NET.Adapter.EFCore/ 

![image](https://user-images.githubusercontent.com/4054836/62019641-63700b00-b1f2-11e9-90b5-aa9a319b8df7.png)

do you have any thought about the package name? or do you think we should publish this package using the official Casbin account?

I'm now going to setup the CI/CD config and finally use travis to publish this package to nuget when a new tag was created.

**Comment by hsluoyz** [comment]
Hi @xcaptain , thanks for the contribution. We should publish the package within Casbin account. I have added you, it's pending.

![image](https://user-images.githubusercontent.com/3787410/62020002-ca41f400-b1f3-11e9-9b87-b59fbec3ec55.png)

**Comment by hsluoyz** [comment]
Hi @xcaptain ,

> do you have any thought about the package name? or do you think we should publish this package using the official Casbin account?

I'm not very familiar with C#. I think your name ``Casbin.NET.Adaprer.EFCore`` has followed the naming convention for .NET projects. Please use the Casbin organization account to publish it.

> I'm now going to setup the CI/CD config and finally use travis to publish this package to nuget when a new tag was created.

But before publishing to nuget, you may want to fix the code coverage badge. Currently, the Travis script doesn't send code coverage report to coveralls.

![image](https://user-images.githubusercontent.com/3787410/62228959-3fc6e380-b3f1-11e9-9b4a-5b2540b4c23a.png)

**Comment by xcaptain** [comment]
@hsluoyz Thanks for setting travis and codecov, 
Can you login into https://www.nuget.org/account/apikeys using the official casbin account and create  an apikey for travis to publish package? I have a personal account but I think it's not very appropriate to use my account to publish this package, after all I don't own this project.

![image](https://user-images.githubusercontent.com/4054836/62287018-8ff28400-b48b-11e9-9367-e428baf32779.png)

After that you need to create an travis environment variable using this key 

![image](https://user-images.githubusercontent.com/4054836/62287142-d8aa3d00-b48b-11e9-93a1-9d075c4a3b22.png)

The key name should be `TRAVIS_CASBIN_NUGET_KEY`, it's defined in `.travis.yml` and then I think travis will be ready to do the publish work.

As for the coverall setup, I need some time to learn, never done any code coverage work for dotnet project before.

**Comment by hsluoyz** [comment]
@xcaptain , you are the Administrator for nuget's Casbin org. I think you do it by yourself :)

**Comment by hsluoyz** [comment]
@xcaptain can you join our QQ group? https://casbin.org/en/help

**Comment by hsluoyz** [comment]
@xcaptain @huazhikui can we develop another adapter for EF?

**Comment by AaqibAhamed** [comment]
> This project is still under development, but basic RBAC functions have been tested on my own
> projects, but still a lot of things need to be done, includes:
> 
> * [x]  `RemoveFilteredPolicy` api
> * [x]  `SavePolicy` api
> * [x]  Make `CasbinRule` model configurable from application code, which means the table name, the column names can be changed. see #6
> * [x]  more unit tests #7
> * [x]  A consistent package id and namespace to publish to nuget or github package registry
> * [ ]  Update to .NET Core and EFCore 3.1 #12
> * [ ]  Code coverage badge doesn't work yet.
> * [ ]  No README.
> * [ ]  No nuget badge, download times badge.
> 
> I'm a little busy in the day time but would try to optimize this project

 Update to .NET Core and EFCore 3.1 #12 .This issue #12  has been sorted.

**Comment by AaqibAhamed** [comment]
@xcaptain @hsluoyz 
Please update the Roadmap for completed tasks and close completed issues.

**Comment by xcaptain** [comment]
Thanks, updated now.

**Comment by hsluoyz** [comment]
@xcaptain can you update the completed items?

**Comment by xcaptain** [comment]
@hsluoyz Updated, seems like the last remaining task is the code coverage.
